/* Public Turnstile sitekey only. No credentials or raw birth records are sent. */
(()=>{'use strict';
const endpoint='https://youpengxun-free-reading.xunertion.workers.dev/interpret';
const sitekey='0x4AAAAAAFHK2LFogg1xpn1i';
let active=null,widget=null,revision=0;
const style=document.createElement('style');style.textContent='.online-reading{margin:24px 0;padding:20px;background:#fffdf8;color:#332a42;border:1px solid #d9cde4;border-radius:16px}.online-reading h3{font-size:22px}.online-reading select,.online-reading button{max-width:100%;padding:10px;margin:8px 0;border:1px solid #887397;border-radius:8px;background:#f6f0fa;color:#332a42}.online-reading pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.7 inherit}.online-reading label{display:block;margin:12px 0}.online-reading .answer{white-space:pre-wrap;font-size:15px;line-height:1.9}.online-reading button:disabled{opacity:.5}';document.head.append(style);
let scriptPromise;
function load(){if(window.turnstile)return Promise.resolve();if(!scriptPromise)scriptPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.onload=resolve;s.onerror=()=>{scriptPromise=null;s.remove();reject(Error('验证组件加载失败，请检查网络后重试。'));};document.head.append(s);});return scriptPromise;}
function clear(){revision++;if(active)active.abort();if(widget!==null&&window.turnstile){window.turnstile.remove(widget);widget=null;}document.getElementById('online-reading')?.remove();}
window.addEventListener('ypx:chart-ready',e=>{
clear();const version=revision;const a=e.detail?.analysis,p=a?.pillars;if(!p)return;
const section=document.createElement('section');section.id='online-reading';section.className='online-reading';
section.innerHTML='<h3>AI 补充解读 · 免费试用</h3><p>先选择想了解的盘面，查看资料后再发送。AI 解释传统象义，不重新排盘，也不能验证命运或保证预测准确。</p><label>解读主题 <select aria-label="AI解读主题"><option value="bazi">八字结构</option></select></label><details><summary>查看将发送的盘面资料</summary><pre></pre></details><label><input type="checkbox"> 我同意将上列盘面资料发送给 Cloudflare Workers AI。不会发送姓名、原始生日、联系方式或本地案例库。</label><button type="button" class="verify">加载人机验证</button><div class="challenge"></div><button type="button" class="send" disabled>生成 AI 解读</button><p role="status" aria-live="polite"></p><div class="answer"></div>';
document.getElementById('unified-report')?.append(section);
const select=section.querySelector('select'),consent=section.querySelector('input'),send=section.querySelector('.send'),status=section.querySelector('[role=status]'),out=section.querySelector('.answer');let token='',facts=[],topic='八字结构';
const palaces=e.detail?.ziwei?.astrolabe?.palaces||[];
palaces.forEach((pal,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent='紫微 · '+pal.name;select.append(o);});
function update(){token='';send.disabled=true;out.textContent='';status.textContent='';if(active)active.abort();if(widget!==null)window.turnstile.reset(widget);consent.checked=false;
if(select.value==='bazi'){topic='八字结构';facts=['本次仅提供本命四柱，不含大运流年，不能推断具体月份事件。'];['year','month','day','hour'].forEach((key,i)=>{const x=p[key];if(x)facts.push(['年柱','月柱','日柱','时柱'][i]+':'+x.stem+x.branch);});}
else {topic='紫微宫位';const i=Number(select.value),pal=palaces[i];facts=['解读目标：'+pal.name+'。仅本命盘，不含运限。'];[i,(i+4)%12,(i+8)%12,(i+6)%12].forEach((j,k)=>{const q=palaces[j];facts.push(['本宫','三合宫','三合宫','对宫'][k]+':'+q.name);['majorStars','minorStars','adjectiveStars'].forEach(group=>{const stars=q[group]||[];for(let n=0;n<stars.length;n+=4)facts.push(q.name+'星曜：'+stars.slice(n,n+4).map(s=>s.name+(s.brightness?'〔'+s.brightness+'〕':'')+(s.mutagen?' 生年'+s.mutagen:'')).join('、'));});});}
facts=facts.slice(0,30).map(x=>x.slice(0,180));section.querySelector('pre').textContent=facts.join('\n');}
update();select.onchange=update;consent.onchange=()=>{send.disabled=!consent.checked||!token;};
section.querySelector('.verify').onclick=async()=>{if(!consent.checked){status.textContent='请先查看盘面资料并勾选同意。';return;}status.textContent='正在加载验证…';try{await load();if(version!==revision)return;if(widget!==null){window.turnstile.reset(widget);return;}widget=window.turnstile.render(section.querySelector('.challenge'),{sitekey,action:'interpret',size:'flexible',callback:t=>{token=t;send.disabled=!consent.checked;status.textContent='验证完成，可以生成解读。';},'expired-callback':()=>{token='';send.disabled=true;status.textContent='验证已过期，请重新验证。';},'error-callback':()=>{token='';send.disabled=true;status.textContent='验证失败，请重新加载验证。';}});}catch(err){status.textContent=err.message;}};
send.onclick=async()=>{if(!token||!consent.checked)return;const controller=new AbortController();active=controller;const timeout=setTimeout(()=>controller.abort(),60000);send.disabled=true;select.disabled=true;out.textContent='';status.textContent='AI 正在解读，请稍候…';try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,facts,consent:true,token}),signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'服务暂不可用');if(typeof data.answer!=='string'||!data.answer.trim())throw Error('未获得有效解读');if(version!==revision)return;out.textContent=data.answer;status.textContent='AI 生成内容，请结合实际情况判断。';}catch(err){if(version===revision)status.textContent=err.name==='AbortError'?'请求已取消或等待超时，可重新验证后重试。本地解读仍可使用。':err.message+'；本地解读仍可使用。';}finally{clearTimeout(timeout);select.disabled=false;token='';send.disabled=true;if(version===revision&&widget!==null)window.turnstile.reset(widget);}};
});
document.addEventListener('click',e=>{if(e.target.closest?.('#uf-go'))clear();},true);
})();
